sudo : required
services :
  -docker

before_install : 
      - docker build -t ilyeselayeb/testclient -f ./client/Dockerfile.dev ./client

script:
      - docker run ilyeselayeb/testclient npm test -- --coverage
    
after_sucees: 
      - docker build -t ilyeselayeb/client -f ./client
      - docker build -t ilyeselayeb/nginx -f ./nginx
      - docker build -t ilyeselayeb/server -f ./server
      - docker build -t ilyeselayeb/worker -f ./worker
 
      - echo "$DOCKER_PASSWORD" | login -u "$DOCKER_ID" --passord-stdin

      - docker push   ilyeselayeb/client
      - docker push   ilyeselayeb/nginx
      - docker push   ilyeselayeb/server
      - docker push   ilyeselayeb/worker



