sudo : required
services :
  -docker:

    before_install : 
      - docker build -t ilyes/testclient -f ./client/Dockerfile.dev

    script:
      - docker run ilyes/testclient npm test -- --coverage
    
    after_sucees: 
      - docker build -t ilyes/client -f ./client
      - docker build -t ilyes/nginx -f ./nginx
      - docker build -t ilyes/server -f ./server
      - docker build -t ilyes/worker -f ./worker
 